name: Report Render Deployment

on:
  push:
    branches:
      - mongo_db

jobs:
  deployment-status:
    runs-on: ubuntu-latest
    steps:
      - name: Start Deployment
        id: deployment                # 👈 Give this step an ID
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.sha }}
          env_url: https://portfoli0-9n2k.onrender.com
          logs: https://dashboard.render.com/web/srv-d1uverer433s73f5tj4g/logs

      - name: Finish Deployment
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          env: production
          ref: ${{ github.sha }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}  # 👈 Fix
          env_url: https://portfoli0-9n2k.onrender.com
          logs: https://dashboard.render.com/web/srv-d1uverer433s73f5tj4g/logs