name: Report Render Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment-status:
    runs-on: ubuntu-latest
    steps:
      - name: Start Deployment
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.sha }}
          target-url: https://portfoli0-9n2k.onrender.com
          log-url: https://dashboard.render.com/web/srv-d1uverer433s73f5tj4g/logs

      - name: Finish Deployment
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          env: production
          ref: ${{ github.sha }}
          target-url: https://your-app-name.onrender.com
          log-url: https://dashboard.render.com/web/srv-XXXX/logs